### ISSUE TITLE
Week 20 DESIGN

### ISSUE THREAD

**Issue by alexac54767** [alexac54767/Fitness_4_Baddies#10]
**To-do:**

Individual:

- [ ] MCQ test (possibly due Tuesday) <- GOOD REFLECTION
- [ ] blog about role with project
- [ ] 5.1 and 5.2 hacks (save for later <- pretty easy)

Group:

- [x] add form to inspo (add images/quotes)
- [ ] make delete/edit buttons on tables
- [x] make presentation ([similar to this w screenshots and bullet points](https://srihitakott1213.github.io/TeamBaddies/lesson/week18))
- [ ] make a "memory" (highlights of presentation) and include NOTES FROM TUESDAY TUTORIAL
