### ISSUE TITLE
Ava- Week 21 Checklist

### ISSUE THREAD

**Issue by avac54765** [alexac54767/Fitness_4_Baddies#18]
Inspo page

Backend:

- [x] add to users.py (create a class, add setter/getter, testers, etc.)
- [x] run main.py and test data table with sq.lite
- [x] use postman to get data

Frontend:
- [x] create HTML5 table for quotes
- [x] add api get/other things to get data
- [ ] figure out how to connect frontend/backend
- [ ] test frontend/backend connection
- [ ] debug
