### ISSUE TITLE
Alexa- Week 21 To-Do

### ISSUE THREAD

**Issue by alexac54767** [alexac54767/Fitness_4_Baddies#19]
ISPE Page

Backend:

- [x] add to users.py (create a class, add setter/getter, testers, etc.)
- [x] run main.py and test data table with sq.lite
- [ ] use postman to get data

Frontend:

- [ ] create HTML5 table for quotes
- [ ] add api get/other things to get data
- [ ] figure out how to connect frontend/backend
- [ ] test frontend/backend connection
- [ ] debug
