### ISSUE TITLE
Ava- Week 17 Progress and To-Do

### ISSUE THREAD

**Issue by avac54765** [alexac54767/Fitness_4_Baddies#2]
Ava:

- [x] edit _config.yml (title, link, theme, description)
- [x] edit theme, sass, CSS (SASS, _assets/css/style.css and CSS customization within style.css)
- [x] Agile Manifesto
- [x] make inspo page
- [x] make grades page with form for input
- [x] customize _layouts/default.html
- [x]  Jekyll build (local host)
- [x] edit image layouts (SASS, _assets/css/style.css and CSS customization within style.css)
- [x] submission grading
