### ISSUE TITLE
Alexa Week 23 To-Do

### ISSUE THREAD

**Issue by alexac54767** [alexac54767/Fitness_4_Baddies#22]
Deployment:
- [ ] [CI/CU Deployment](github pages)](https://nighthawkcoders.github.io/APCSP//2023/02/08/PBL-cd_ci.html)
- [ ] AWS deployment (Sri)

Full Stack:
- [x] trouble shoot: failed to fetch <- cors issue (DELETED CORS BUT PUT BACK AFTER DEPLOYMENT)
![cors issue](https://user-images.githubusercontent.com/111482658/218582598-0437351e-d5ad-4e87-8242-20e31a2ee5fe.jpg)
- [ ] add data!
- [x] make individual database
- [x] make individual api
- [x] edit api/database to match ISPE (ISPE in ISPEs issue in ISPE.py?)
