### ISSUE TITLE
Ava - Week 23 Final Project To-do

### ISSUE THREAD

**Issue by avac54765** [alexac54767/Fitness_4_Baddies#23]
Frontend

- [ ] debug fetching to the backend (CORS issue?)
- [ ] add testing data

Backend

- [ ] create new databse/api?????
- [ ] deploy backend on AWS (Sri?)
- [ ] make sure create function works
- [ ] figure out CRUD (editing the data)

ask about having one team database/api with separate classes
ask about deploying frontend
