### ISSUE TITLE
Team To-Do Week 18

### ISSUE THREAD

**Issue by avac54765** [alexac54767/Fitness_4_Baddies#7]
- [x] finish backend hacks individually
- [x] start writing get and setter functions for workout log page and grades page
- [x] create login button
- [x] write backend for login
