### ISSUE TITLE
Project to-do and Questions

### ISSUE THREAD

**Issue by alexac54767** [alexac54767/Fitness_4_Baddies#9]
Questions:
- If we want users to have individual data, is it okay to just add more vars under the user class/dictionary
- ^ if so, can we have multiple workouts? Or will the setter function only allow one (like username/password)
-  Can we have multiple tables in frontend that access different info from the same class/dictionary?
  - repeat same frontend code for each table (posting to backend/js to fill table)?
  - delete the password parts for the tables (not user login)?

To-do:

- [x] change forms so only name (not first and last)
- [x] edit code to adjust to that change^
- [x] edit tester in frontend (test table w/o backend working)
- [x] make inspirational quote form
- [ ] make frontend code for other tables too (post to backend and fill table)
- [x] make login+sign up pages with forms
- [ ] fix styling of sign-up button (on login page)
- [ ] add vars to users.py for tables?
- [ ] make 30-60 sec debugging video (HACK)
- [ ] make 30-60 sec API video (HACK)

Test:
- [ ] table fills out with testing code
- [ ] run man.py and can view sqlite file (spreadsheet w data appears?)
- [ ] final goal: input in frontend -> table (goes through backend)
